modLoader="javafml"
loaderVersion="[1,)"
license="All rights reserved"
[[mods]]
modId="animalgarden_bison" 
version="1.0.0"
displayName="Animal Garden - bison"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/animal-garden-bison"
credits="" 
authors="aquarius_playz" 

description='''
More info at the website.
'''

[[dependencies.animalgarden_bison]]
    modId="aquarius_libs"
    mandatory=true
    versionRange="[1.0.0,]"
    ordering="NONE"
    side="BOTH"