weight=10 #int | default: 10
min=1 #int | default: 1
max=1 #int | default: 1
sound_volume=1.0 #float | default: 1.0
is_always_persistent=false #boolean | default: false
check_area_size_for_mobs_of_same_type_when_spawning=32 #int | default: 32
max_mob_number_of_same_type_around_area_when_spawning=1 #int | default: 1

