weight=25 #int | default: 25
min=1 #int | default: 1
max=4 #int | default: 4
is_always_persistent=true #boolean | default: true
check_area_size_for_mobs_of_same_type_when_spawning=0 #int | default: 0
max_mob_number_of_same_type_around_area_when_spawning=5 #int | default: 5
sound_volume=0.5 #float | default: 0.5
play_sound_distance=20 #int | default: 20
idle_sound_minimum_interval=15 #int | default: 15
enable_behavior_chat_messages=true #boolean | default: true
start_to_rest_after_x_sec=30 #int | default: 30
random_sleep_interval=500 #int | default: 500

