redpanda.weight=20 #int | default: 20
redpanda.min=1 #int | default: 1
redpanda.max=1 #int | default: 1
redpanda_himalayan.weight=20 #int | default: 20
redpanda_himalayan.min=1 #int | default: 1
redpanda_himalayan.max=1 #int | default: 1
sound_volume=1.0 #float | default: 1.0

