weight=10 #int | default: 10
min=2 #int | default: 2
max=5 #int | default: 5
is_always_persistent=true #boolean | default: true
check_area_size_for_mobs_of_same_type_when_spawning=0 #int | default: 0
max_mob_number_of_same_type_around_area_when_spawning=3 #int | default: 3
sound_volume=0.5 #float | default: 0.5
play_sound_distance=30 #int | default: 30
idle_sound_minimum_interval=60 #int | default: 60
enable_behavior_chat_messages=true #boolean | default: true
start_to_rest_after_x_sec=30 #int | default: 30
random_sleep_interval=500 #int | default: 500

