weight=15 #int | default: 15
min=1 #int | default: 1
max=1 #int | default: 1
is_always_persistent=true #boolean | default: true
check_area_size_for_mobs_of_same_type_when_spawning=16 #int | default: 16
max_mob_number_of_same_type_around_area_when_spawning=1 #int | default: 1
sound_volume=0.3 #float | default: 0.3
play_sound_distance=20 #int | default: 20
idle_sound_minimum_interval=20 #int | default: 20
enable_behavior_chat_messages=true #boolean | default: true
can_be_tamed=false #boolean | default: false
random_sleep_interval=1000 #int | default: 1000
random_attack_chance=500 #int | default: 500
can_attack_randomly=true #boolean | default: true
can_attack_randomly_after_taming=true #boolean | default: true
can_have_algae=true #boolean | default: true

