modLoader="javafml"
loaderVersion="[1,)"
license="All rights reserved"
[[mods]]
modId="animalgarden_bongo" 
version="1.0.1"
displayName="Animal Garden - bongo"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/animal-garden-bongo"
credits="" 
authors="aquarius_playz" 

description='''
More info at the website.
'''

[[dependencies.animalgarden_bongo]]
    modId="aquarius_libs"
    type="required"
    versionRange="[1.0.0,]"
    ordering="NONE"
    side="BOTH"